### ISSUE TITLE
Failure with rubocop-performance

### ISSUE THREAD

**Issue by andyw8** [michaelherold/codeclimate-haml_lint#13]
In RuboCop 0.68, the performance cops were moved out to a separate gem, so to use them I have added this to my RuboCop config:

```
require: rubocop-performance
```

This fails because the rubocop-performance gem is not part of the engine.

**Comment by michaelherold** [comment]
Hmm. I suppose following CodeClimate's Rubocop engine would be a good idea. It looks like [they include several plugins](https://github.com/codeclimate/codeclimate-rubocop/blob/channel/rubocop-0-74/Gemfile). I'd be happy to include the same set!
