### ISSUE TITLE
Severity Levels

### ISSUE THREAD

**Issue by andyw8** [michaelherold/codeclimate-haml_lint#4]
I got an email from Code Climate with an alarming title: **1 new severe issue found**

So I opened it:

> Inconsistent indentation: 2 spaces used for indentation

:grin:

I see the current mapping is:

```ruby
HAML_LINT_TO_CODE_CLIMATE = {
  error: "critical",
  warning: "normal",
}
```

As haml-lint doesn't deal with security issues, I think it's difficult to justify anything being at the "critical" or "blocker" level. Even "major" seems too strong.

How about this:

```ruby
HAML_LINT_TO_CODE_CLIMATE = {
  error: "minor",
  warning: "info",
}
```

(Sidenote: Is "normal" valid? It's not listed in the [spec](https://github.com/codeclimate/spec/blob/master/SPEC.md))

**Comment by michaelherold** [comment]
😆  That's a pretty funny reason to fail with a severe notice!

I'm using [this version of the spec](https://github.com/codeclimate/spec/blob/v0.2.0/SPEC.md), which does use "normal" as a level. In fact, it only has three levels: "info", "normal", and "critical".

Looks like it's time to update the spec version! I think the syntax linter should be a major, critical, or blocker and everything else (off the top of my head) will likely be minor or less.

**Comment by michaelherold** [comment]
I should have included that you can see the version of the CC spec that the engine is running against in the `engine.json` file.
